FROM starefossen/ruby-node

MAINTAINER yukito ohira

WORKDIR /hobbycart
ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    ROOT_PATH=/hobbycart \
    BUNDLE_PATH=vendor/bundle \
    BUNDLE_JOBS=4

RUN gem update
COPY . /hobbycart

RUN bundle install && yarn install
RUN bundle exec rake assets:precompile

EXPOSE 3000

CMD bundle exec rails s -b 0.0.0.0 -e production

